Add Release-Notes for 1.32.1
nginx/unit-docs pull request #131
Opened 2024-03-25 13:24 UTC by tippexs

2024-03-25 13:36 UTC, tarynmusgrave approved these changes
This looks good to me.

2024-03-25 14:03 UTC, Jcahilltorre commented
Nit for future releases: the branch name should be `release-1.32.1` (to be able to protect all the branches that match the release-xxx pattern)

2024-03-25 14:42 UTC, Jcahilltorre approved these changes

2024-03-25 14:42 UTC, Jcahilltorre commented on source/news/2024/index.rst
> +   :description: Version 1.32.1 is a maintenance release, fixing bugs in the new WebAssembly Language Module and in our NJS implementation.
```suggestion
   :description: Version 1.32.1 is a maintenance release that fixes bugs in the new WebAssembly Language Module and in our NJS implementation.
```

2024-03-25 14:42 UTC, Jcahilltorre commented on source/news/2024/unit-1.32.1-released.rst
> +NGINX Unit 1.32.1 is a maintenance release, fixing bugs in the new WebAssembly Language Module and in our NJS implementation.
```suggestion
NGINX Unit 1.32.1 is a maintenance release that fixes bugs in the new WebAssembly Language Module and in our NJS implementation.
```

2024-03-25 14:42 UTC, Jcahilltorre commented on source/news/2024/unit-1.32.1-released.rst
> +After deploying a new Wasm Component binary to disk the restart will trigger a reload of the component in Unit without restarting the server.
```suggestion
After deploying a new Wasm Component binary to disk, the restart will trigger a reload of the component in Unit without restarting the server.
```

2024-03-25 14:42 UTC, Jcahilltorre commented on source/news/2024/unit-1.32.1-released.rst
> +As restarts will work independently of the application type, the behavior shipped with **1.32.0** was not right and fixed with this release.
```suggestion
As restarts will work independently of the application type, the behavior shipped with **1.32.0** was not right. It has been fixed in this release.
```

2024-03-25 14:42 UTC, Jcahilltorre commented on source/news/2024/unit-1.32.1-released.rst
> +With **1.32.0** we have released the possibility to access all Unit variables form inside NJS.
```suggestion
In **1.32.0** we added the possibility to access all Unit variables form inside NJS.
```

2024-03-25 14:42 UTC, Jcahilltorre commented on source/news/2024/unit-1.32.1-released.rst
> +As reported in GitHub issue `#1169 <https://github.com/nginx/unit/issues/1169>`__ the variables are cached and will hold the wrong value, which is definitely not the way this feature should work. Wit
```suggestion
As reported in GitHub issue `#1169 <https://github.com/nginx/unit/issues/1169>`__ the variables were cached and would hold the wrong value, which is not how this feature should work. With version 1.32.1, we have fixed this issue.
```

2024-03-26 18:52 UTC, danielledeleo requested changes
source/conf.py:8
```
version = '1.32.0'
release_date = 'Feb 27, 2024'
```

These need to be bumped before release if not in this PR, then in another.

2024-03-26 18:55 UTC, Jcahilltorre commented
> source/conf.py:8
> 
> ```
> version = '1.32.0'
> release_date = 'Feb 27, 2024'
> ```
> 
> These need to be bumped before release if not in this PR, then in another.

I have bumped them, please remove the change request.

2024-03-26 19:01 UTC, danielledeleo approved these changes

2024-03-27 10:21 UTC, merged