Update symfony.rst
nginx/unit-docs pull request #149
Opened 2024-05-24 13:32 UTC by andreybolonin

https://symfony.com/releases

2024-07-02 09:19 UTC, javorszky requested changes
Once you rebase over current main or otherwise resolve the conflicts and respond to the comment about version, I'm happy to merge this in.

I'm also open to leaving it at 8.1 if there's a strong argument for it.

Thank you for taking the time on this! 🙂

2024-07-02 09:19 UTC, javorszky commented on source/howto/symfony.rst
> +.. |mod| replace:: PHP 8.1+
Hi there! I see that 8.1 is needed for Symfony's long term support release 6.4.9 that will be supported until Novemebr 2026.

The current stable release needs 8.2+.

I would suggest updating this to. Folks needing long term support are most probably already aware that php 8.1 is their requirement.

2024-07-02 09:19 UTC, javorszky commented on source/howto/symfony.rst
> +.. |mod| replace:: PHP 8.1+
```suggestion
.. |mod| replace:: PHP 8.2+
```

2024-07-13 11:53 UTC, andreybolonin commented
@javorszky updated

2024-07-30 12:42 UTC, javorszky approved these changes

2024-07-30 12:42 UTC, merged

2024-07-30 12:42 UTC, javorszky commented
> @javorszky updated

Thank you! Approved and merged :)