docs: add CLI doc draft
nginx/unit-docs pull request #161
Opened 2024-08-01 15:11 UTC by Jcahilltorre

Adds the doc for the unitctl cli

To do:
- Add the links to the binaries or remove the section
- Decide whether to add the compiling instructions here or keep them as a link to the repo

2024-08-01 16:57 UTC, avahahn commented
I see that we have a global section for options. I am curious if there should perhaps be a section for options per subcommand?

2024-08-01 17:02 UTC, avahahn requested changes
I see that we have a global section for options. I am curious if there should perhaps be a section for options per subcommand?

I also note that there is a subcommand missing (export).

2024-08-01 17:06 UTC, avahahn commented
> Decide whether to add the compiling instructions here or keep them as a link to the repo

My vote is to link to the repo for this. The instructions may change along with planned improvements to the unitctl design. If we link to the repo unitctl readme then readers will always be pointed to the most up to date instructions.

2024-08-01 17:08 UTC, avahahn commented
> Add the links to the binaries or remove the section

I believe a good option here is to link to the github releases section in the Unit repo, as that will populate with download links for the CLI.

2024-08-06 13:04 UTC, Jcahilltorre commented
> > Add the links to the binaries or remove the section
> 
> I believe a good option here is to link to the github releases section in the Unit repo, as that will populate with download links for the CLI.

I don't see a releases section in the Unit repo currently

2024-08-06 13:06 UTC, Jcahilltorre commented
> I see that we have a global section for options. I am curious if there should perhaps be a section for options per subcommand?
> 
> I also note that there is a subcommand missing (export).

the list of command and options is based on the documentation in the repo. The export command is missing there too. Where could I get a comprehensive list of the options for each command?

2024-08-06 21:15 UTC, travisamartin commented on source/unitctl.rst
> +We provide unitctl binaries for Linux (both ARM64 and X64) and MacOS systems.
```suggestion
Unitctl binaries are available for Linux (ARM64 and X64) and MacOS systems.
```

2024-08-06 21:16 UTC, travisamartin commented on source/unitctl.rst
> +<https://github.com/nginx/unit/releases>`_
```suggestion
Download the latest binaries from the `Unit GitHub releases page <https://github.com/nginx/unit/releases>`_.
```

2024-08-06 21:17 UTC, travisamartin commented on source/unitctl.rst
> +<https://github.com/nginx/unit/tree/master/tools/unitctl>`_.
```suggestion
To build unitctl from source, follow the instructions in the `unitctl repository <https://github.com/nginx/unit/tree/master/tools/unitctl>`_.
```

2024-08-06 21:18 UTC, travisamartin commented on source/unitctl.rst
> +Unit. The following is a list of the available commands:
```suggestion
The unitctl CLI offers several commands to interact with Unit. Here are the available commands:
```

2024-08-06 21:20 UTC, travisamartin commented on source/unitctl.rst
> +     - Get the current status of the Unit
```suggestion
     - Get the current status of Unit
```

2024-08-06 21:24 UTC, travisamartin commented on source/unitctl.rst
> +deploy new instances of Unit.
```suggestion
The **instances** command lets you list all running Unit processes and
deploy new instances of Unit.
```

2024-08-06 21:25 UTC, travisamartin commented on source/unitctl.rst
> +The **instances** command has the following options:
```suggestion
The **instances** command has the following option:
```

2024-08-06 21:26 UTC, travisamartin commented on source/unitctl.rst
> +the following:
```suggestion
Running unitcl with the **instances** command shows output similar to this:
```

2024-08-06 21:36 UTC, Jcahilltorre commented on source/unitctl.rst
> +     - Get the current status of the Unit
this was a leftover from a previous version of the sentence that mentioned the Unit instance itselv

2024-08-06 21:37 UTC, travisamartin commented on source/unitctl.rst
> +using the **new** option and three arguments:
```suggestion
You can use the **new** option with three arguments to deploy a new instance of Unit:
```

2024-08-06 21:40 UTC, travisamartin commented on source/unitctl.rst
> +   a TCP address with port.
```suggestion
1. **Control API path**: A file path for a Unix socket or a TCP address with port.
```

2024-08-06 21:54 UTC, travisamartin commented on source/unitctl.rst
> +   images. For example: **unit:wasm**.
```suggestion
   - if you specify a directory, the Unit container will mount it to **/var/run** internally. 
     The control socket and pid file are accessible from the host. Example: **/tmp/2**.
   - If you specify a TCP address, the Unit container will listen on this
     address and port. Example: **127.0.0.1:7171**.

2. **Application path**. The Unit container will mount this path in read-only mode
   to **/www** internally. This setup allows you to configure the Unit
   container to expose an application stored on the host. Example: **$(pwd)**.

3. **Image tag**: Unitctl will deploy this image, enabling you use custom
   images. For example: **unit:wasm**.
```

2024-08-06 22:04 UTC, Jcahilltorre commented on source/unitctl.rst
> +Download the latest binaries from the `Unit GitHub releases page <https://github.com/nginx/unit/releases>`_.
```suggestion
Download the latest binaries from the `Unit GitHub releases page
<https://github.com/nginx/unit/releases>`_.
```

2024-08-06 22:04 UTC, Jcahilltorre commented on source/unitctl.rst
> +To build unitctl from source, follow the instructions in the `unitctl repository <https://github.com/nginx/unit/tree/master/tools/unitctl>`_.
```suggestion
To build unitctl from source, follow the instructions in the `unitctl repository
<https://github.com/nginx/unit/tree/master/tools/unitctl>`_.
```

2024-08-06 22:18 UTC, travisamartin commented on source/unitctl.rst
> +      $ unitctl -s '127.0.0.1:8001' -s /run/nginx-unit.control.sock app list
```suggestion
+++++++++++++++++++++++++++++
List and restart running apps
+++++++++++++++++++++++++++++

The **app** command lets you list and restart active applications.

Options
-------

The **app** command has the following options:

.. list-table::
   :header-rows: 1

   * - Option
     - Description

   * - **list**
     - List all active applications

   * - **reload <APP_NAME>**
     - Restart the specified application

To list active applications, run:

.. code-block:: console

   $ unitctl app list
   {
     "wasm": {
        "type": "wasm-wasi-component",
        "component": "/www/wasmapp-proxy-component.wasm"
     }
   }

To restart an application, run:

.. code-block:: console

   $ unitctl app reload wasm
   {
      "success": "Ok"
   }

.. note::

   This command supports operating on multiple instances of Unit at once. To do
   this, use the **-s** option multiple times with different values:

   .. code-block:: console

      $ unitctl -s '127.0.0.1:8001' -s /run/nginx-unit.control.sock app list
```

2024-08-06 22:23 UTC, Jcahilltorre commented on source/unitctl.rst
> +      $ unitctl -s '127.0.0.1:8001' -s /run/nginx-unit.control.sock app list
The instances command also has an (optional) option in a table. I feel if we apply this change we also should have an Options header in the previous command for consistency

2024-08-06 22:24 UTC, travisamartin commented on source/unitctl.rst
> +To list all active listeners, run the following command:
```suggestion
To list all active listeners, run:
```

2024-08-06 22:24 UTC, Jcahilltorre commented on source/unitctl.rst
> +      $ unitctl -s '127.0.0.1:8001' -s /run/nginx-unit.control.sock app list
in L105

2024-08-06 22:25 UTC, travisamartin commented on source/unitctl.rst
> +To get the current status of the Unit, run the following command:
```suggestion
To get the current status of the Unit, run:
```

2024-08-06 22:36 UTC, travisamartin commented on source/unitctl.rst
> +use of stdin as shown in the example below.
```suggestion
With the **execute** command, Unitctl can accept custom request payloads and
query specified API endpoints with them. Use the **-f** flag to pass the request 
payload as a filename or **-** to denote stdin, as shown in the example below.
```

2024-08-06 22:38 UTC, travisamartin commented on source/unitctl.rst
> +      $ unitctl -s '127.0.0.1:8001' -s /run/nginx-unit.control.sock app list
Agreed, both should have the header. I just learned how to add headers in rst -- this is my first one. I can add the other.

2024-08-06 22:53 UTC, ac000 commented on source/unitctl.rst
> +Unitctl binaries are available for Linux (ARM64 and X64) and MacOS systems.
MacOS should be spelt 'macOS'.

2024-08-06 23:02 UTC, Jcahilltorre commented on source/unitctl.rst
> +Unitctl binaries are available for Linux (ARM64 and X64) and MacOS systems.
```suggestion
Unitctl binaries are available for Linux (ARM64 and X64) and macOS systems.
```

2024-08-06 23:34 UTC, travisamartin commented on source/unitctl.rst
> +   This command does not support operating on multiple instances of Unit at once.
```suggestion
Unitctl can fetch the configuration from a running instance of Unit and load it
in a preconfigured editor on your command line using the **edit** command.

Unitctl tries to use the editor configured with the **EDITOR** environment
variable, but defaults to vim, emacs, nano, vi, or pico if **EDITOR** is not set.

To edit the current configuration, run:

.. code-block:: console

   $ unitctl edit

The configuration loads into the editor, allowing you to make any necessary
changes. Once you save and close the editor, you see the following output:

.. code-block:: console

   {
   "success": "Reconfiguration done."
   }

.. note::

   This command does not support operating on multiple instances of Unit at once.
```

2024-08-06 23:40 UTC, travisamartin commented on source/unitctl.rst
> +To export the configuration, run the following command:
```suggestion
The **import** command lets Unitctl read configuration files, certificates, and
NJS modules from a directory. Unitctl then converts these files into a payload
to reconfigure a Unit daemon.

To export the configuration, run:
```

2024-08-06 23:43 UTC, travisamartin commented on source/unitctl.rst
> +used with **-f -** as shown in the following examples:
```suggestion
The **export** command queries a control API to fetch the running configuration
and NJS modules from a Unit process. The output does not include the currently
stored certificate bundles due to a technical limitation. The output is saved
as a tarball with the filename specified by the **-f** argument. You can also
use standard output with **-f -**, as shown in the examples below:
```

2024-08-06 23:45 UTC, travisamartin commented on source/unitctl.rst
> +All commands support waiting on unix sockets for availability:
```suggestion
All commands support waiting for Unix sockets to become available:
```

2024-08-07 19:01 UTC, avahahn commented
> > > Add the links to the binaries or remove the section
> > 
> > 
> > I believe a good option here is to link to the github releases section in the Unit repo, as that will populate with download links for the CLI.
> 
> I don't see a releases section in the Unit repo currently

https://github.com/nginx/unit/releases
The section is there, and will be populated with the upcoming 1.33 release

2024-08-07 19:03 UTC, avahahn commented
> > I see that we have a global section for options. I am curious if there should perhaps be a section for options per subcommand?
> > I also note that there is a subcommand missing (export).
> 
> the list of command and options is based on the documentation in the repo. The export command is missing there too. Where could I get a comprehensive list of the options for each command?

https://github.com/nginx/unit/tree/master/tools/unitctl#export-configuration-from-a-running-unit-instance

It is listed here.

2024-08-07 19:16 UTC, avahahn approved these changes

2024-08-07 19:54 UTC, travisamartin approved these changes

2024-08-28 14:36 UTC, merged