draft: Release 1.33 news doc
nginx/unit-docs pull request #168
Opened 2024-08-27 16:43 UTC by Jcahilltorre

Adds the Release 1.33 news document

Currently a draft.

To do:

- [ ]  Add release introductory paragraph
- [ ] Add the highlighted new features and changes
- [ ] Add the 'Changes in behavior and other updates'
- [ ] Confirm the date of release and update as necessary

2024-08-27 18:28 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +making Unit better! With 1.32.0 we would like to send a shout out to:
1.33.0

2024-08-27 18:33 UTC, Jcahilltorre commented on source/news/2024/unit-1.33.0-released.rst
> +making Unit better! With 1.32.0 we would like to send a shout out to:
```suggestion
making Unit better! With 1.33.0 we would like to send a shout out to:
```

2024-08-28 16:11 UTC, ADubhlaoich approved these changes

2024-08-28 16:12 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +   connections. By default Unit creates the same number of threads as there
```suggestion
   connections. By default, Unit creates the same number of threads as there
```

2024-08-28 16:20 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +:ref:`unitctl <unitctl>` is a powerful, Rust-based CLI tool that allows you to
what does "powerful" mean? it's markety sounding.

2024-08-28 16:21 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +Length Required**. This feature is experimental and can
What does "experimental" mean? Is there any risk that needs to be called out?

2024-08-28 16:22 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +  use the OS's default: 4096 for Linux 5.4 and later; 128 for older versions.
```suggestion
* On Linux, we now default to a **listen(2)** backlog of `-1`, which means we
  use the OS's default: `4096` for Linux 5.4 and later; `128` for older versions.
```

2024-08-28 16:23 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +only supported compilers for building Unit.
```suggestion
We removed support for a several lesser-known compilers. GCC and Clang are now the
only supported compilers for building Unit.
```

2024-08-28 16:23 UTC, Jcahilltorre commented on source/news/2024/unit-1.33.0-released.rst
> +:ref:`unitctl <unitctl>` is a powerful, Rust-based CLI tool that allows you to
This is in line with the tone and style used in these release blogs previously.

2024-08-28 16:24 UTC, Jcahilltorre commented on source/news/2024/unit-1.33.0-released.rst
> +Length Required**. This feature is experimental and can
@ac000 might be able to address that

2024-08-28 16:25 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +didn't explicitly set the -std= option, as we were supporting CentOS 7 (which is now
there's inconsisencies in how options are style. Sometimes, they're bold. Sometimes, they're in-line code. Sometimes, they're plain text. I recommend in-line code for all of them.

Above, it's in-line code.

<img width="581" alt="image" src="https://github.com/user-attachments/assets/d80c04c2-b83f-47d3-82ee-cb8e4fb7c7aa">

2024-08-28 16:26 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +Special thanks to Arjun for his fuzzing work.
Is "fuzzing" a generally known term for our global audience?

2024-08-28 16:26 UTC, travisamartin commented on source/unitctl.rst
> +This CLI is a powerful tool that allows you to deploy, manage, and configure
Same comment as above w/r/t "powerful"

2024-08-28 16:27 UTC, travisamartin approved these changes
Some minor nits, but overall looks good.

2024-08-28 16:31 UTC, Jcahilltorre commented on source/news/2024/unit-1.33.0-released.rst
> +didn't explicitly set the -std= option, as we were supporting CentOS 7 (which is now
I went with bold for consistency with the other release documents.

If there were still options using inline code, it's not intentional

2024-08-28 17:55 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +Length Required**. This feature is experimental and can
Here 'experimental' is the qualifier for why it's not enabled by default.

It's _experimental_ in that it was a quick _temporary_ implementation to fulfil a specific requirement, until a more permanent solution is made.

2024-08-28 18:00 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +only supported compilers for building Unit.
> We removed support for a several lesser-known compilers. GCC and Clang are now the

At least remove the 'a'!

2024-08-28 18:03 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +- Remi Collet
There will hopefully be another name to add to this list!

2024-08-28 18:08 UTC, travisamartin commented on source/news/2024/unit-1.33.0-released.rst
> +only supported compilers for building Unit.
Oops -- thanks for catching that! Fixed in the edit.

2024-08-29 14:05 UTC, Jcahilltorre commented on source/news/2024/unit-1.33.0-released.rst
> +Length Required**. This feature is experimental and can
why not say that instead?

```suggestion
Length Required**. This is a temporary workaround while we work on a long-term improvement, and can
```

2024-08-29 14:22 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +Length Required**. This feature is experimental and can
Think I prefer it the way it is... the alternative text is going too far into the weeds for me...

2024-09-02 10:33 UTC, Jcahilltorre commented on source/news/2024/unit-1.33.0-released.rst
> +Length Required**. This feature is experimental and can
we need to explain what experimental implies one way or another

2024-09-03 18:24 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +Length Required**. This feature is experimental and can
It's not documented and subject to change...

2024-09-04 13:24 UTC, ac000 commented
@Jcahilltorre 

Regarding commit

```
f283a05 fix: fix nav subsections
```

What was it that changed that made _this_ change necessary?

2024-09-04 22:20 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +- Remi Collet
OK, you can add

```
Robbie McKinstry
```

to the list.

2024-09-04 22:38 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +
Another feature to add

```
    *) Feature: the wasm-wasi-component language module now inherits the
       processes environment.
```

2024-09-04 22:40 UTC, ac000 commented on source/news/2024/index.rst
> +   :description: Version 1.33.0 includes two new configuration options and a CLI tool.
`three` new configuration options. 'factory' for Python applications being the third.

2024-09-04 22:55 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +This release introduces two new configuration options:
s/two/three

2024-09-04 22:55 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +
Format as required...

```
 3) factory                                                                     
                                                                                
This can be set under '/applications/<app>/factory'                             
                                                                                
This is a boolean value and if set to 'true', Unit treats 'callable' as         
a factory.                                                                      
                                                                                
The default is 'false'.                                                         
                                                                                
NOTE: Unit does *not* support passing arguments to factories.
```

2024-09-05 13:13 UTC, Jcahilltorre commented on source/conf.py
> +release_date = 'Aug 29, 2024'
```suggestion
release_date = 'Aug 29, 2024'
```
This needs to be updated before merge

2024-09-05 13:13 UTC, Jcahilltorre commented on source/news/2024/index.rst
> +   :date: 2024-08-29
```suggestion
   :date: 2024-08-29
```

Update before merge

2024-09-07 02:43 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +to true.
'true' should probably be bold.

2024-09-09 09:38 UTC, Jcahilltorre commented on source/news/2024/unit-1.33.0-released.rst
> +to true.
```suggestion
to **true**.
```

2024-09-10 04:24 UTC, ac000 commented on source/news/2024/unit-1.33.0-released.rst
> +
New bugfix

```
*) Bugfix: fix a crash when interrupting a download via a proxy.
```

2024-09-17 01:07 UTC, ac000 requested changes

2024-09-17 01:07 UTC, ac000 commented on source/unitctl.rst
> +The **app** command lets you list and restart active applications.
s/app/apps/

2024-09-17 01:07 UTC, ac000 commented on source/unitctl.rst
> +   * - **reload <APP_NAME>**
s/reload/restart/

2024-09-17 10:34 UTC, Jcahilltorre commented on source/unitctl.rst
> +The **app** command lets you list and restart active applications.
```suggestion
The **apps** command lets you list and restart active applications.
```

2024-09-17 10:34 UTC, Jcahilltorre commented on source/unitctl.rst
> +   * - **reload <APP_NAME>**
```suggestion
   * - **restart <APP_NAME>**
```

2024-09-17 12:43 UTC, ac000 requested changes

2024-09-17 12:43 UTC, ac000 commented on source/unitctl.rst
> +   * - **app**
s/app/apps/

2024-09-17 12:43 UTC, ac000 commented on source/unitctl.rst
> +The **app** command has the following options:
s/app/apps/

2024-09-17 12:43 UTC, ac000 commented on source/unitctl.rst
> +   $ unitctl app reload wasm
s/app/apps/
s/reload/restart/

2024-09-17 12:43 UTC, ac000 commented on source/unitctl.rst
> +   $ unitctl app list
s/app/apps/

2024-09-17 14:07 UTC, Jcahilltorre commented on source/unitctl.rst
> +   $ unitctl app reload wasm
```suggestion
   $ unitctl apps restart wasm
```

2024-09-17 14:07 UTC, Jcahilltorre commented on source/unitctl.rst
> +   $ unitctl app list
```suggestion
   $ unitctl apps list
```

2024-09-17 14:07 UTC, Jcahilltorre commented on source/unitctl.rst
> +The **app** command has the following options:
```suggestion
The **apps** command has the following options:
```

2024-09-17 14:08 UTC, Jcahilltorre commented on source/unitctl.rst
> +   * - **app**
```suggestion
   * - **apps**
```

2024-09-17 14:30 UTC, ac000 approved these changes

2024-09-18 14:00 UTC, merged