Add details of non-matching mime type filter behaviour
nginx/unit-docs pull request #66
Opened 2023-11-21 10:07 UTC by javorszky

Closes #63 

* Adds details to main configuration documentation on what happens to mime type filtering when a request's mime type is not matched by any of the rules in the share option.
* Lifts example from the 1.24.0 news item for usage with a fallback option.

Tested locally to make sure formatting and reference links work and go the correct places.

2023-11-21 11:27 UTC, lcrilly requested changes

2023-11-21 11:27 UTC, lcrilly commented on source/configuration.rst
> +        "types": [ "!application/x-httpd-php" ],
I know this is the example from the 1.24.0 news item but I find it a bit contrived. It's much simpler to achieve the same thing with uri-based routing.

A more practical example would be to use the expansiveness of MIME types to send specific response headers for certain file types. `image/*` saves a lot of typing for all the possible file extensions.

A possible example at https://github.com/nginx/unit/discussions/984#discussioncomment-7438412

2023-11-21 11:27 UTC, lcrilly commented on source/configuration.rst
> +        "types": [ "!application/x-httpd-php" ],
Also, using negation in examples requires a bit more cognitive effort so I'd like to find a "smoother" example. Especially as negation was used and explained in the first sample in this section.

2023-11-21 14:13 UTC, lcrilly requested changes

2023-11-21 14:27 UTC, lcrilly commented on source/configuration.rst
> +Here, all requests to :samp:`.pdf` files, all images, all fonts, and all
Suggest aligning this sentence with my proposed set of MIME types and the "web page resources" use case.

2023-11-21 14:57 UTC, andrey-zelenkov commented on source/configuration.rst
> +        "types": [ "!application/x-httpd-php" ],
Side note: almost exactly the same example has already present in the doc under the `Examples` section:
[conf-variable-examples](https://unit.nginx.org/configuration/#conf-variable-examples_)

So probably it makes sense just to fix this example (if we unhappy about it) and provide a link to it instead of expanding this section.

2023-11-21 15:39 UTC, lcrilly commented on source/configuration.rst
> +when the a 40x response would be returned.
s/the a/a

2023-11-21 15:46 UTC, lcrilly commented on source/configuration.rst
> +for serving common web page resources that do not change with cache
I like this explanation, but "with cache" might suggest that Unit is doing the caching. Suggestion:

> This is useful for serving common web page resources that do not change; web browsers and caching proxies are informed that this content should be cached.

2023-11-30 16:27 UTC, andrey-zelenkov reviewed
Looks good.

2023-11-30 16:27 UTC, andrey-zelenkov commented on source/configuration.rst
> +Here, all requests to images, fonts, and any text based files will have
/s/text based/text-based

2023-11-30 16:27 UTC, andrey-zelenkov commented on source/configuration.rst
> +and proxies are informed this content should be cached.
May be better will be:

 informed **that** this ...

2023-12-01 10:39 UTC, javorszky commented on source/configuration.rst
> +Here, all requests to images, fonts, and any text based files will have
Fixed in 11ca8e03

2023-12-01 10:39 UTC, javorszky commented on source/configuration.rst
> +and proxies are informed this content should be cached.
Fixed in 11ca8e03

2023-12-01 10:40 UTC, javorszky commented
Fixed all the change requests and responses, and opened PR #68 from my own fork. Same content as this one.

2023-12-01 10:40 UTC, closed without merging